CREATE TABLE `movie` (
	`MovieID` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY ,
	`ImdbID` VARCHAR(12) NOT NULL UNIQUE,
	`Title` VARCHAR(100) NOT NULL ,
	`Plot` TEXT NOT NULL ,
	`Released` DATE NOT NULL ,
	`Language` VARCHAR(30) NOT NULL ,
	`Runtime` INT NOT NULL ,
	`Trailer`VARCHAR(60) NOT NULL ,
	`ProductionCompany` VARCHAR(30) NOT NULL ,
	`Director` VARCHAR(50) NOT NULL ,
	`Writer` VARCHAR(50) NOT NULL
);

CREATE TABLE `actor` (
	`ActorID` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY ,
	`ImdbLink` VARCHAR(12) NOT NULL UNIQUE ,
	`Name` VARCHAR(50) NOT NULL
);

CREATE TABLE `genre` (
	`GenreID` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY ,
	`Genre` VARCHAR(12) NOT NULL UNIQUE
);

CREATE TABLE `movieactor` (
	`MovieActorID` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY ,
	`MovieID` INT(11) UNSIGNED NOT NULL ,
	`ActorID` INT(11) UNSIGNED NOT NULL ,
	CONSTRAINT `MA_Movie_FK`
	FOREIGN KEY (`MovieID`) REFERENCES `movie` (`MovieID`)
	ON DELETE CASCADE
	ON UPDATE NO ACTION ,
	CONSTRAINT `MA_Actor_FK`
	FOREIGN KEY (`ActorID`) REFERENCES `actor` (`ActorID`)
	ON DELETE CASCADE
	ON UPDATE NO ACTION
);

CREATE TABLE `moviegenre` (
	`MovieGenreID` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY ,
	`MovieID` INT(11) UNSIGNED NOT NULL ,
	`GenreID` INT(11) UNSIGNED NOT NULL ,
	CONSTRAINT `MG_Movie_FK`
	FOREIGN KEY (`MovieID`) REFERENCES `movie` (`MovieID`)
	ON DELETE CASCADE ,
	CONSTRAINT `MG_Genre_FK`
	FOREIGN KEY (`GenreID`) REFERENCES `genre` (`GenreID`)
	ON DELETE CASCADE
);
